/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_opengldemo_tringle_RendererJNI */

#ifndef _Included_com_me_opengldemo_tringle_RendererJNI
#define _Included_com_me_opengldemo_tringle_RendererJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_opengldemo_tringle_RendererJNI
 * Method:    gLESInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_me_opengldemo_tringle_RendererJNI_gLESInit
  (JNIEnv *, jobject);

/*
 * Class:     com_me_opengldemo_tringle_RendererJNI
 * Method:    glESSizeChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_me_opengldemo_tringle_RendererJNI_glESSizeChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_me_opengldemo_tringle_RendererJNI
 * Method:    glESRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_me_opengldemo_tringle_RendererJNI_glESRender
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
